//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kindergarten
    {
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string Postcode { get; set; }
        public string Phone { get; set; }
        public string Email_Address { get; set; }
        public string location { get; set; }
    }
}
